config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/deck', to: 'posts#deck'
  get 'users/:id/followers/', to: 'users#followers', as: 'followers'
  get 'users/:id/following/', to: 'users#following', as: 'following'
  
  resources :account_activations, only: [:edit]

  resources :users do
    member do
      get :follow
      get :unfollow
    end
  end

  resources :posts
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :activation_token
  # before_create :create_activation_digest

  has_secure_password
  has_many :posts

  acts_as_follower
  acts_as_followable

  validates :email,     presence: true, 
                        uniqueness: true
  validates :username,  presence: true, 
                        uniqueness: true,
                        length: { in: 3..15 }

  validates :password,  length: { in: 6..20 }
  validates :password,  confirmation: true
  validates :password,  presence: true, 
                        on: :create, 
                        on: :update, 
                        allow_blank: true
  validates :password_confirmation, 
                        presence: true, 
                        on: :create

  def ratio
    following = self.follow_count.to_f
    followers = self.followers.count.to_f

    if followers == 0
      ratio = "No ratio."
    else
      ratio = (followers / following).round(2)
    end

    return ratio
  end

  private

  # def create_activation_digest
  #   self.activation_token  = User.new_token
  #   self.activation_digest = User.digest(activation_token)
  # end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    if current_user
      @post = Post.new
    else
      flash[:alert] = "You must be logged in first."
      redirect_to login_path
    end
  end

  def create
    @post = Post.new(post_params)
    current_user.posts << @post
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    if @post.delete
      flash[:notice] = "Post was successfully deleted."
      redirect_to :back
    else
      flash[:alert] = "Post could not be deleted."
      redirect_to :back
    end
  end

  def deck
    @posts = Post.all
  end

    private

  def post_params
    params.require(:post).permit(:text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, :notice => "Welcome back, #{user.username}!"
    else
      flash.now[:alert] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, :notice => "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Hipster Parrot, #{@user.username}."
      redirect_to user_path(@user)
    else
      render :new  
    end
  end

  def show
    @user = User.find_by_id(params[:id])

    if @user.posts.count > 0
      @post_count = @user.posts.count
    else
      @post_count = ""
    end
  end

  def follow
    @user = User.find_by_id(params[:id])

    if current_user
      if current_user == @user
        flash[:alert] = "You cannot follow yourself."
      else
        current_user.follow(@user)
        redirect_to :back
        flash[:notice] = "You are now following #{@user.username}."
      end
    else
      flash[:alert] = "You must <a href='/login'>login</a> to follow #{@user.username}.".html_safe
    end
  end



  def unfollow
    @user = User.find(params[:id])

    if current_user
      current_user.stop_following(@user)
      redirect_to :back
      flash[:notice] = "You are no longer following #{@user.username}."
    else
      flash[:alert] = "You must <a href='/login'>login</a> to unfollow #{@user.username}.".html_safe
    end
  end

  def followers
    @user = User.find_by_id(params[:id])
  end

  def following
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="hero">
  <div class="hero-text">
    <h1>Welcome to Hipster Parrot.</h1>
    <h2>Like Twitter, but before it was cool.</h2>
    <% if !current_user %>
      <%= link_to 'Sign Up', new_user_path, class: "btn btn-success btn-lg" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3>Mainstream</h3>
      <p>The Mainstream is a global feed, where everyone's posts are shown. Some posts are cool. Others, maybe not.</p>
    </div>
    <div class="col-md-4">
      <h3>The Deck</h3>
      <p>The Deck is your personal feed. Only posts by people you follow will be shown.</p>
    </div>
    <div class="col-md-4">
      <h3>Ratio</h3>
      <p>Your ratio of followers to following. The higher the better.</p>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div id="messages">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/"><%= image_tag 'logo.png' %></a>
        <% if current_user %>
          <a href="/posts/new"><button type="button" class="btn btn-success navbar-btn" data-toggle="modal" data-target="#newPost">
            <span class="glyphicon glyphicon-pencil"></span>
          </button></a>
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to 'Mainstream', posts_path %></li>
            <li><%= link_to 'Deck', deck_path %></li>
            <li><%= link_to 'Profile', user_path(session[:user_id]) %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <li><h4 class="navbar-text"><span class="label label-success">Logged in as <%= current_user.username %></span></h4></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_path %></li>
            <li><%= link_to 'Log in', login_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipster Parrot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%= render "layouts/navigation" %>

  <%= render "layouts/messages" %>

  <%= yield %>

</body>
</html>

app/views/posts/deck.html.erb
<div id="deck">
  <div id="deck-feed">
    <h1>Deck</h1>
    <h4><em>Posts from people you follow.</em></h4>

    <% if @posts.count > 0 %>
      <% @posts.reverse.each do |post| %>
        <% if current_user && current_user.following?(post.user) %>
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title"><%= link_to "@" + post.user.username, post.user %> | <span><%= link_to 'Unfollow', unfollow_user_path(:id => post.user.id), class: "btn btn-default btn-xs" %></span></h3>
            </div>
            <div class="panel-body">
              <p><%= post.text %>
                <% if @user == current_user %>
                  <span> | <%= link_to("Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}) %> </span></p>  
                <% end %>
              <p><small><em>Posted on <%= post.created_at.strftime('%A, %B %e at %m:%M %p') %>.</em></small></p>
            </div>
          </div>
        <% end %>
      <% end %>

    <% else %>
      <h3>No posts.</h3>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div id="mainstream">
  <div id="mainstream-feed">
    <h1>Mainstream</h1>
    <h4><em>Posts from everyone, cool or not.</em></h4>

    <% if @posts.count > 0 %>
      <% @posts.reverse.each do |post| %>
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">
              <%= link_to "@" + post.user.username, post.user %> | 
              <% if post.user != current_user %>
                <% if current_user.following?(post.user) %>
                  <span><%= link_to 'Unfollow', unfollow_user_path(:id => post.user.id), class: "btn btn-default btn-xs" %></span>
                <% elsif %>
                  <span><%= link_to 'Follow', follow_user_path(:id => post.user.id), class: "btn btn-success btn-xs" %></span>
                <% end %>
              <% else %>
                <span class="label label-default">This is you</span>
              <% end %>
            </h3>
          </div>
          <div class="panel-body">
            <p>
              <%= post.text %>
              <% if post.user == current_user %>
                <span> | <%= link_to("Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}) %> </span>
            </p>  
              <% end %>
            <p><small><em>Posted on <%= post.created_at.strftime('%A, %B %e at %m:%M %p') %>.</em></small></p>
          </div>
        </div>
      <% end %>

    <% else %>
      <h3>No posts.</h3>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div id="new-post">
  <h1>Add New Post</h1>

  <%= form_for @post, url: {action: "create", controller: "posts"}, html: {class: "form-horizontal"} do |f| %>
    <div class="col-sm-4">
      <p><%= f.text_field :text, class: 'form-control' %></p>
      <p><%= f.submit nil, :class => 'btn btn-success' %></p>
    </div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="newPost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Post</h4>
      </div>
      <div class="modal-body">
        <%= form_for @post, url: {action: "create", controller: "posts"}, html: {class: "form-horizontal"} do |f| %>
          <div class="form-group">
            <%= f.label :Post, class: 'col-sm-2 control-label' %>
            <div class="col-sm-4">
              <%= f.text_field :text, class: 'form-control' %>
            </div>
          </div>
            <div>
              <%= f.submit nil, :class => 'btn btn-primary col-sm-offset-2', "data-dismiss" => "modal", "aria-hidden" => "true" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div id="follow-container">
  <div id="follow-feed">
    <h1>@<%= @user.username %>'s followers</h1>
    <% @user.followers.each do |follower| %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= link_to "@" + follower.username, follower %>
            <% if follower.id == session[:user_id] %>
              <span class="label label-success">This is your profile</span>
            <% else %>
              <% if current_user %>
                <% if current_user.following?(follower) %>
                  <span><%= link_to 'Unfollow', unfollow_user_path(:id => follower.id), class: "btn btn-default btn-xs" %></span>
                <% else %>
                  <span><%= link_to 'Follow', follow_user_path(:id => follower.id), class: "btn btn-success btn-xs" %></span>
                <% end %>
              <% end %>
            <% end %>
          </h3>
        </div>
        <div class="panel-body">
          <%= link_to followers_path(:id => follower.id) do %>
            <div class="stat-left">
              <small>Followers</small>
              <h4><%= follower.followers.count %></h4>
            </div>
          <% end %>
          <%= link_to following_path(:id => follower.id) do %>
            <div class="stat-center">
              <small>Following</small>
              <h4><%= follower.follow_count %></h4>
            </div>
          <% end %>
          <div class="stat-right">
            <small>Ratio</small>
            <h4><%= follower.ratio %></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/following.html.erb
<div id="follow-container">
  <div id="follow-feed">
    <h1>Following @<%= @user.username %></h1>
    <% @user.all_following.each do |following| %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= link_to "@" + following.username, following %>
            <% if following.id == session[:user_id] %>
              <span class="label label-success">This is your profile</span>
            <% else %>
              <% if current_user %>
                <% if current_user.following?(following) %>
                  <span><%= link_to 'Unfollow', unfollow_user_path(:id => following.id), class: "btn btn-default btn-xs" %></span>
                <% else %>
                  <span><%= link_to 'Follow', follow_user_path(:id => following.id), class: "btn btn-success btn-xs" %></span>
                <% end %>
              <% end %>
            <% end %>
          </h3>
        </div>
        <div class="panel-body">
          <%= link_to followers_path(:id => following.id) do %>
            <div class="stat-left">
              <small>Followers</small>
              <h4><%= following.followers.count %></h4>
            </div>
          <% end %>
          <%= link_to following_path(:id => following.id) do %>
            <div class="stat-center">
              <small>Following</small>
              <h4><%= following.follow_count %></h4>
            </div>
          <% end %>
          <div class="stat-right">
            <small>Ratio</small>
            <h4><%= following.ratio %></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div id="signup">
  <h1>Sign Up</h1>
  <%= form_for @user, url: {action: "create"}, html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
       <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prevented the account from being created.
          </h2>
          <ul>
            <% @user.errors.full_messages.reverse.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :username, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_field :username, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :Email, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :Password, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-4">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :Confirm_Password, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>
      <div>
        <%= f.submit nil, :class => 'btn btn-primary col-sm-offset-2' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="clear"></div>
<div id="profile-container">
  <div class="user-stats">
    <% if @user.id == session[:user_id] %>
      <h1>This is your profile</h1>
    <% else %>
      <h1><%= @user.username %>'s profile
      <% if current_user %>
        <% if current_user.following?(@user) %>
          <%= link_to 'Unfollow', unfollow_user_path, class: "btn btn-default" %>
        <% elsif  %>
          <%= link_to 'Follow', follow_user_path, class: "btn btn-success" %>
        <% end %>
      <% end %></h1>
    <% end %>

    <%= link_to followers_path do %>
      <div class="stat-left">
        <small>Followers</small>
        <h4><%= @user.followers.count %></h4>
      </div>
    <% end %>
    <%= link_to following_path do %>
      <div class="stat-center">
        <small>Following</small>
        <h4><%= @user.follow_count %></h4>
      </div>
    <% end %>
    <div class="stat-right">
      <small>Ratio</small>
      <h4><%= @user.ratio %></h4>
    </div>
  </div>

  <div id="user-feed">
    <h1>Feed</h1>
    <% if @user.posts.count > 0 %>
      <% @user.posts.reverse.each do |post| %>
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Posted on <%= post.created_at.strftime('%A, %B %e at %m:%M %p') %>.</h3>
          </div>
          <div class="panel-body">
            <p><%= post.text %>
              <% if @user == current_user %>
                <span> | <%= link_to("Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}) %> </span></p>  
              <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3>No posts.</h3>
    <% end %>
  </div>
</div>